services:
  node1:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: node1
    environment:
      - PORT=3001
    volumes:
      - ./app:/app
    expose:
      - "3001"
    command: ["node", "server.js"]

  node2:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: node2
    environment:
      - PORT=3002
    volumes:
      - ./app:/app
    expose:
      - "3002"
    command: ["node", "server.js"]

  node3:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: node3
    environment:
      - PORT=3003
    volumes:
      - ./app:/app
    expose:
      - "3003"
    command: ["node", "server.js"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node1
      - node2
      - node3
